-- Manual Supabase SQL migration: multi-device Web Push subscriptions.
-- Review and run this file independently. It does not execute the Family CONTRACT migration.

BEGIN;

DO $preflight$
BEGIN
    IF to_regclass('public.users') IS NULL THEN
        RAISE EXCEPTION 'Preflight failed: public.users does not exist';
    END IF;

    IF to_regclass('public.push_subscriptions') IS NOT NULL THEN
        RAISE EXCEPTION 'Preflight failed: public.push_subscriptions already exists';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'users'
          AND column_name = 'id'
          AND data_type = 'integer'
          AND is_nullable = 'NO'
    ) THEN
        RAISE EXCEPTION 'Preflight failed: public.users.id is not a non-null integer';
    END IF;
END
$preflight$;

CREATE TABLE public.push_subscriptions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    endpoint text NOT NULL,
    p256dh text NOT NULL,
    auth text NOT NULL,
    expiration_time timestamptz NULL,
    created_at timestamptz NOT NULL DEFAULT NOW(),
    updated_at timestamptz NOT NULL DEFAULT NOW(),
    CONSTRAINT push_subscriptions_user_id_fkey
        FOREIGN KEY (user_id)
        REFERENCES public.users(id)
        ON DELETE CASCADE,
    CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint),
    CONSTRAINT push_subscriptions_endpoint_nonempty_check
        CHECK (length(btrim(endpoint)) > 0),
    CONSTRAINT push_subscriptions_p256dh_nonempty_check
        CHECK (length(p256dh) > 0),
    CONSTRAINT push_subscriptions_auth_nonempty_check
        CHECK (length(auth) > 0)
);

CREATE INDEX push_subscriptions_user_id_idx
    ON public.push_subscriptions (user_id);

REVOKE ALL PRIVILEGES
ON TABLE public.push_subscriptions
FROM anon, authenticated;

COMMIT;
