import { useCallback, useEffect, useRef, useState } from 'react'
import { DASHBOARD_CATEGORIES, categoryPosition, type DashboardCategory } from '../dashboard/rotarySelector'
import { DashboardCategoryIcon } from './DashboardCategoryIcon'
import { FamilyScreen } from './FamilyScreen'
import { ReservationCenterScreen } from './ReservationCenterScreen'
import { HistoryScreen } from './HistoryScreen'
import { VehiclesScreen } from './VehiclesScreen'
import { SettingsScreen } from './SettingsScreen'

function WedgeLayer({ onOpen }: { onOpen: (category: DashboardCategory) => void }) {
 const paths = ['M50 50 L22 0 A50 50 0 0 1 78 0 Z','M50 50 L78 0 A50 50 0 0 1 100 66 Z','M50 50 L100 66 A50 50 0 0 1 78 100 Z','M50 50 L78 100 A50 50 0 0 1 22 100 Z','M50 50 L22 100 A50 50 0 0 1 0 66 Z']
 return <svg className="dashboard-wedge-layer" viewBox="0 0 100 100" aria-label="קטגוריות לוח הבקרה">{paths.map((d,i)=><path key={d} role="button" tabIndex={0} d={d} aria-label={`פתיחת ${DASHBOARD_CATEGORIES[i].label}`} onClick={()=>onOpen(DASHBOARD_CATEGORIES[i])} onKeyDown={e=>{if(e.key==='Enter'||e.key===' ')onOpen(DASHBOARD_CATEGORIES[i])}} />)}<circle className="dashboard-wedge-center" cx="50" cy="50" r="17" /></svg>
}
export function DashboardScreen({ open, userName, userEmail, accessToken, version, carDataRefreshVersion, onClose, onLogout }: { open:boolean; userName:string; userEmail:string; accessToken:string; version:string; carDataRefreshVersion:number; onClose:()=>void; onLogout:()=>Promise<void> }) {
 const closeButtonRef=useRef<HTMLButtonElement|null>(null); const frame=useRef<number|null>(null); const [activeCategory,setActiveCategory]=useState<DashboardCategory|null>(null); const [categoryOpen,setCategoryOpen]=useState(false); const [loggingOut,setLoggingOut]=useState(false)
 const closeCategory=useCallback(()=>{if(frame.current!==null)window.cancelAnimationFrame(frame.current);setCategoryOpen(false);window.requestAnimationFrame(()=>closeButtonRef.current?.focus({preventScroll:true}))},[])
 const openCategory=useCallback((category:DashboardCategory)=>{if(frame.current!==null)window.cancelAnimationFrame(frame.current);setActiveCategory(category);frame.current=window.requestAnimationFrame(()=>{setCategoryOpen(true);frame.current=null})},[])
 useEffect(()=>()=>{if(frame.current!==null)window.cancelAnimationFrame(frame.current)},[])
 useEffect(()=>{if(!open)return;if(!categoryOpen)closeButtonRef.current?.focus({preventScroll:true});const h=(e:globalThis.KeyboardEvent)=>{if(e.key==='Escape'){if(categoryOpen)closeCategory();else onClose()}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[categoryOpen,closeCategory,onClose,open])
 const handleLogout=async()=>{if(loggingOut)return;setLoggingOut(true);try{await onLogout()}finally{setLoggingOut(false)}}
 return <section className={`dashboard-screen${open?' is-open':''}`} dir="rtl" role="dialog" aria-modal="true" aria-label="לוח הבקרה" aria-hidden={!open} inert={!open}><div className="dashboard-content" inert={categoryOpen}><header className="dashboard-header"><button ref={closeButtonRef} type="button" onClick={onClose} aria-label="חזרה לצ׳אט"><span className="dashboard-menu-glyph" aria-hidden="true"><i /><i /><i /></span></button><strong>Family Car Agent</strong><span aria-hidden="true" /></header><p className="dashboard-greeting">היי, {userName}</p><div className="dashboard-selector-area"><div className="dashboard-category-orbit"><div className="rotary-glass-disc" aria-hidden="true" /><WedgeLayer onOpen={openCategory} />{DASHBOARD_CATEGORIES.map((category,index)=>{const p=categoryPosition(index,34);return <button key={category.id} type="button" className="dashboard-category-button" style={{left: p.left + '%', top: p.top + '%'}} onClick={()=>openCategory(category)} aria-label={`פתיחת ${category.label}`}><DashboardCategoryIcon icon={category.icon}/><span>{category.label}</span></button>})}<div className="dashboard-category-center" aria-hidden="true" /></div></div><footer className="dashboard-footer"><button type="button" className="dashboard-logout" disabled={loggingOut} onClick={()=>void handleLogout()}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M10 5H5v14h5M14 8l4 4-4 4M8 12h10"/></svg><span>{loggingOut?'מתנתקים…':'התנתקות'}</span></button><small>v{version}</small></footer></div>{activeCategory?(activeCategory.id==='family'?<FamilyScreen accessToken={accessToken} open={categoryOpen} onBack={closeCategory}/>:activeCategory.id==='reservations'?<ReservationCenterScreen accessToken={accessToken} open={categoryOpen} onBack={closeCategory}/>:activeCategory.id==='history'?<HistoryScreen accessToken={accessToken} open={categoryOpen} refreshVersion={carDataRefreshVersion} onBack={closeCategory}/>:activeCategory.id==='cars'?<VehiclesScreen open={categoryOpen} onBack={closeCategory}/>:<SettingsScreen open={categoryOpen} userName={userName} userEmail={userEmail} accessToken={accessToken} version={version} onBack={closeCategory} onOpenFamily={()=>openCategory(DASHBOARD_CATEGORIES[0])} onLogout={handleLogout}/>):null}</section>
}
