"""Offline checkpoint checks. Never import backend code or connect to a DB."""
import copy
from pathlib import Path
import re
import runpy
import unittest

ROOT = Path(__file__).resolve().parents[1]
CHECKPOINT = ROOT / "supabase/bootstrap/2026-09-30"
MODULE = runpy.run_path(str(CHECKPOINT / "validate_checkpoint.py"))
SQL = (CHECKPOINT / "current_schema.sql").read_text(encoding="utf-8")


class DatabaseCheckpointTests(unittest.TestCase):
    def test_exact_inventory(self):
        tables = re.findall(r'^CREATE TABLE public\."([^"]+)"', SQL, re.M)
        self.assertEqual(tables, list(MODULE["TABLES"]))
        self.assertEqual(len(re.findall(r'^ALTER TABLE .* ADD CONSTRAINT ', SQL, re.M)), 151)
        self.assertEqual(len(re.findall(r'^CREATE (?:UNIQUE )?INDEX ', SQL, re.M)), 39)
        self.assertEqual(SQL.count('-- Constraint-backed index:'), 49)
        self.assertEqual(len(re.findall(r'^CREATE FUNCTION ', SQL, re.M)), 5)
        self.assertEqual(len(re.findall(r'^CREATE TRIGGER ', SQL, re.M)), 4)
        self.assertEqual(len(re.findall(r'^CREATE POLICY ', SQL, re.M)), 1)

    def test_guards_and_no_provider_recreation(self):
        self.assertTrue(SQL.rstrip().endswith('COMMIT;'))
        self.assertLess(SQL.index('$checkpoint_guard$;'), SQL.index('CREATE SEQUENCE'))
        self.assertIn("fca.allow_empty_checkpoint", SQL)
        self.assertIn("< 170000", SQL)
        for forbidden in ('CREATE TABLE auth.', 'CREATE TABLE realtime.', 'CREATE ROLE',
                          'CREATE EXTENSION', 'ALTER DEFAULT PRIVILEGES', 'DROP ',
                          'CREATE OR REPLACE', 'setval('):
            self.assertFalse(forbidden in SQL, forbidden)
        self.assertNotRegex(SQL, r'CREATE (?:TABLE|SEQUENCE|INDEX) IF NOT EXISTS')
        self.assertNotIn('onboarding_sessions', SQL)

    def test_keys_before_foreign_keys_and_tables_before_constraints(self):
        statements = re.findall(r'^ALTER TABLE .* ADD CONSTRAINT .*;', SQL, re.M)
        first_fk = next(i for i, s in enumerate(statements) if ' FOREIGN KEY ' in s)
        self.assertTrue(all(' FOREIGN KEY ' in s for s in statements[first_fk:]))
        self.assertLess(SQL.rindex('CREATE TABLE'), SQL.index(' ADD CONSTRAINT '))
        self.assertIn('ON DELETE SET NULL (start_event_id)', SQL)
        self.assertIn('ON DELETE SET NULL (end_event_id)', SQL)
        self.assertEqual(sum(' DEFERRABLE' in s for s in statements), 3)

    def test_exact_security_shape(self):
        self.assertEqual(len(re.findall(r'^ALTER TABLE .* ENABLE ROW LEVEL SECURITY;', SQL, re.M)), 13)
        self.assertEqual(len(re.findall(r'^ALTER TABLE .* DISABLE ROW LEVEL SECURITY;', SQL, re.M)), 10)
        self.assertEqual(SQL.count('NO FORCE ROW LEVEL SECURITY;'), 23)
        self.assertEqual(len(re.findall(r'^REVOKE ALL PRIVILEGES \(', SQL, re.M)), 23)
        self.assertEqual(SQL.count('TRIGGER, MAINTAIN ON TABLE'), 23)
        self.assertEqual(SQL.count('GRANT SELECT, UPDATE, USAGE ON SEQUENCE'), 12)
        self.assertNotIn('WITH GRANT OPTION', SQL)
        grants = [s for s in SQL.splitlines() if s.startswith('GRANT ') and
                  ('anon' in s or 'authenticated' in s)]
        self.assertEqual(len(grants), 1)
        self.assertIn('can_receive_car_status_topic(text)', grants[0])
        self.assertIn('actual @> expected AND actual <@ expected', SQL)

    def test_sequences_and_only_capacity_seeds(self):
        self.assertEqual(SQL.count('GENERATED BY DEFAULT AS IDENTITY'), 5)
        self.assertEqual(len(re.findall(r'^CREATE SEQUENCE ', SQL, re.M)), 7)
        self.assertEqual(SQL.count('MAXVALUE 9223372036854775807'), 5)
        self.assertNotIn('9223372036854776000', SQL)
        inserts = re.findall(r'^INSERT INTO .*;', SQL, re.M)
        self.assertEqual(inserts, [
            "INSERT INTO public.gemini_capacity_policies (capacity_pool, max_concurrency) VALUES ('gemini-default', 50);",
            "INSERT INTO public.geocoding_capacity_policies (capacity_pool, max_concurrency) VALUES ('google-geocoding', 20);",
        ])

    def test_current_realtime_and_guards(self):
        self.assertNotIn('CREATE TRIGGER car_events_', SQL)
        self.assertIn("WHEN ((new.admission_outcome = 'accepted'::text))", SQL)
        self.assertIn('BEFORE UPDATE OF vehicle_reconciliation_generation, vehicle_finalized_through', SQL)
        self.assertIn('AFTER DELETE ON public.users FOR EACH ROW', SQL)
        self.assertIn("'family:' || OLD.family_id::text || ':car-status', true", SQL)
        self.assertIn('u.auth_user_id = (SELECT auth.uid())', SQL)

    def test_function_bodies_match_reconciled_tracked_sql(self):
        sources = [ROOT / 'supabase/schema_baseline/current_schema.sql',
                   ROOT / 'supabase/manual_migrations/2026092001_vehicle_identity_foundation.sql',
                   ROOT / 'supabase/manual_migrations/2026092502_carplay_vehicle_authority.sql']
        history = '\n'.join(p.read_text(encoding='utf-8') for p in sources)
        for name in MODULE['FUNCTIONS']:
            pattern = r'CREATE (?:OR REPLACE )?FUNCTION public\.' + name + r'\(.*?\$function\$(.*?)\$function\$'
            self.assertEqual(re.search(pattern, SQL, re.S)[1], re.search(pattern, history, re.S)[1])


@unittest.skipUnless(MODULE['DEFAULT_EVIDENCE'].is_dir(), 'Operator-local ignored evidence unavailable')
class CaptureComparisonTests(unittest.TestCase):
    def setUp(self):
        self.evidence = MODULE['load_evidence'](MODULE['DEFAULT_EVIDENCE'])

    def test_complete_evidence_comparison(self):
        self.assertEqual(SQL, MODULE['render'](self.evidence))

    def test_missing_inventory_rejected(self):
        self.evidence['columns'].pop()
        with self.assertRaises(ValueError):
            MODULE['render'](self.evidence)

    def test_changed_acl_rejected(self):
        self.evidence['acl']['relations'][0]['acl'] = '{anon=r/postgres}'
        with self.assertRaises(ValueError):
            MODULE['render'](self.evidence)

    def test_missing_lossless_sequence_rejected(self):
        self.evidence['targeted']['bigint_sequences'].pop()
        with self.assertRaises(ValueError):
            MODULE['render'](self.evidence)

    def test_semantic_evidence_mutations_change_comparison(self):
        for area in ('columns', 'constraint', 'function', 'trigger'):
            e = copy.deepcopy(self.evidence)
            if area == 'columns':
                e['columns'][0]['not_null'] = False
            elif area == 'constraint':
                e['structure']['constraints'][0]['definition'] = 'CHECK (true)'
            elif area == 'function':
                e['targeted']['functions'][0]['definition'] += '\n-- drift'
            else:
                e['targeted']['triggers'][0]['definition'] += ' -- drift'
            self.assertNotEqual(SQL, MODULE['render'](e), area)


if __name__ == '__main__':
    unittest.main()
