"""Read-only static evidence reconciliation. Never connects to a database."""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent
AUDIT = ROOT.parent / "schema_audit"
SQL = (ROOT / "current_schema.sql").read_text(encoding="utf-8")


def rows(name):
    header = None
    result = []
    for line in (AUDIT / f"production_{name}.md").read_text(encoding="utf-8").splitlines():
        if not line.startswith("|"):
            continue
        cells = [s.strip().replace(r"\|", "|") for s in re.split(r"(?<!\\)\|", line[1:line.rfind("|")])]
        if all(re.fullmatch(r"[- :]+", s) for s in cells):
            continue
        if cells[0] in {"table_name", "schema_name", "table_schema", "function_name", "schemaname", "role_name"}:
            header = cells
            continue
        assert header and len(cells) == len(header), (name, line)
        result.append(dict(zip(header, cells)))
    return result


def q(value):
    return '"' + value.replace('"', '""') + '"'


columns = {}
for c in rows("columns"):
    key = (c["table_name"], c["column_name"])
    assert key not in columns or columns[key] == c, f"Conflicting column capture: {key}"
    columns[key] = c
tables = [t for t in rows("objects_rls") if t["object_type"] == "table"]
sequences = rows("sequences")
constraints = rows("constraints")
indexes = rows("indexes")
privileges = rows("privileges")
assert len(tables) == 17 and len(columns) == 116 and len(sequences) == 8
assert set(t["object_name"] for t in tables) == set(c["table_name"] for c in columns.values())
assert len(re.findall(r"^CREATE TABLE public\.", SQL, re.M)) == 17

for t in tables:
    name = t["object_name"]
    expected = []
    for c in sorted((c for c in columns.values() if c["table_name"] == name), key=lambda c: int(c["ordinal_position"])):
        assert c["is_generated"] == "NEVER" and c["generation_expression"] == "null"
        assert c["udt_schema"] == "pg_catalog" and c["character_maximum_length"] == "null"
        line = f'    {q(c["column_name"])} {c["data_type"]}'
        if c["collation_name"] != "null":
            line += f' COLLATE {q(c["collation_name"])}'
        if c["is_identity"] == "YES":
            s = next(s for s in sequences if s["owned_by_table"] == name)
            assert c["identity_generation"] == "BY DEFAULT"
            for a, b in [("identity_start", "start_value"), ("identity_increment", "increment_by"), ("identity_minimum", "min_value"), ("identity_maximum", "max_value")]:
                assert c[a] == s[b]
            line += f' GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.{q(s["sequence_name"])} START WITH {s["start_value"]} INCREMENT BY {s["increment_by"]} MINVALUE {s["min_value"]} MAXVALUE {s["max_value"]} CACHE {s["cache_size"]} NO CYCLE)'
        elif c["column_default"] != "null":
            line += f' DEFAULT {c["column_default"]}'
        if c["is_nullable"] == "NO":
            line += " NOT NULL"
        expected.append(line)
    block = f'CREATE TABLE public.{q(name)} (\n' + ",\n".join(expected) + "\n);"
    assert block in SQL, f"Column mismatch: {name}"
    assert f'ALTER TABLE public.{q(name)} OWNER TO {t["owner"]};' in SQL
    mode = "ENABLE" if t["rls_enabled"] == "true" else "DISABLE"
    assert f'ALTER TABLE public.{q(name)} {mode} ROW LEVEL SECURITY;' in SQL
    assert t["rls_forced"] == "false"
    assert f'ALTER TABLE public.{q(name)} NO FORCE ROW LEVEL SECURITY;' in SQL
    assert f'REVOKE ALL PRIVILEGES ON TABLE public.{q(name)} FROM PUBLIC, anon, authenticated, service_role;' in SQL
    for role in ("postgres", "service_role"):
        grants = [r for r in privileges if r.get("table_name") == name and r.get("grantee") == role]
        assert len(grants) == 7
        suffix = " WITH GRANT OPTION" if all(r["is_grantable"] == "YES" for r in grants) else ""
        assert f'GRANT {", ".join(r["privilege_type"] for r in grants)} ON TABLE public.{q(name)} TO {role}{suffix};' in SQL

for s in sequences:
    assert s["owner"] == "postgres" and s["is_cycled"] == "false"
    assert s["column_default"] == columns[(s["owned_by_table"], s["owned_by_column"])]["column_default"]
    if s["owned_by_table"] != "push_subscriptions":
        typ = "integer" if s["max_value"] == "2147483647" else "bigint"
        assert f'CREATE SEQUENCE public.{q(s["sequence_name"])} AS {typ} START WITH {s["start_value"]} INCREMENT BY {s["increment_by"]} MINVALUE {s["min_value"]} MAXVALUE {s["max_value"]} CACHE {s["cache_size"]} NO CYCLE;' in SQL
        assert f'ALTER SEQUENCE public.{q(s["sequence_name"])} OWNED BY public.{q(s["owned_by_table"])}.{q(s["owned_by_column"])};' in SQL
    grants = [r for r in privileges if r.get("sequence_name") == s["sequence_name"]]
    assert {(r["grantee"], r["privilege_type"], r["is_grantable"]) for r in grants} == {(role, perm, "false") for role in ("postgres", "service_role") for perm in ("SELECT", "UPDATE", "USAGE")}
    assert f'GRANT SELECT, UPDATE, USAGE ON SEQUENCE public.{q(s["sequence_name"])} TO postgres, service_role;' in SQL
    assert f'REVOKE ALL PRIVILEGES ON SEQUENCE public.{q(s["sequence_name"])} FROM PUBLIC, anon, authenticated, service_role;' in SQL

for c in constraints:
    assert (c["is_deferrable"], c["initially_deferred"], c["is_validated"]) == ("false", "false", "true")
    assert f'ALTER TABLE public.{q(c["table_name"])} ADD CONSTRAINT {q(c["constraint_name"])} {c["definition"]};' in SQL
for i in indexes:
    assert i["index_owner"] == "postgres" and i["is_valid"] == i["is_ready"] == "true"
    backed = any(c["constraint_name"] == i["index_name"] and c["constraint_type"] in ("PRIMARY KEY", "UNIQUE") for c in constraints)
    prefix = "-- Constraint-backed captured definition: " if backed else ""
    assert prefix + i["index_definition"] + ";" in SQL

for r in rows("functions_realtime"):
    if "function_definition" in r:
        assert r["function_definition"].replace("<br>", "\n").strip() + ";" in SQL
        signature = f'public.{r["function_name"]}(' + ("text" if r["identity_arguments"] else "") + ")"
        assert f'ALTER FUNCTION {signature} OWNER TO {r["owner"]};' in SQL
        assert f'REVOKE ALL PRIVILEGES ON FUNCTION {signature} FROM PUBLIC, anon, authenticated, service_role;' in SQL
        recipients = "postgres, service_role" + (", anon, authenticated" if r["identity_arguments"] else "")
        assert f'GRANT EXECUTE ON FUNCTION {signature} TO {recipients};' in SQL
    if "trigger_definition" in r:
        assert r["trigger_definition"] + ";" in SQL
    if "policyname" in r:
        assert f'CREATE POLICY {q(r["policyname"])} ON realtime.messages AS {r["permissive"]} FOR SELECT TO authenticated USING ({r["qual"]});' in SQL
assert "No explicit column-level ACLs returned." in (AUDIT / "production_privileges.md").read_text(encoding="utf-8")
assert SQL.count("INSERT INTO") == 2
assert "VALUES ('gemini-default', 50)" in SQL and "VALUES ('google-geocoding', 20)" in SQL
assert not re.search(r"CREATE EXTENSION|ALTER EXTENSION|ALTER DEFAULT PRIVILEGES|CREATE PUBLICATION|ALTER PUBLICATION|messages_\d|setval\(", SQL, re.I)
assert "DO NOT APPLY TO THE EXISTING FCA PRODUCTION DATABASE" in SQL
assert "fca.allow_empty_baseline" in SQL
print("PASS: 17 tables / 116 columns / 8 sequences / 86 constraints / 45 indexes; RLS, captured ACLs, Realtime definitions and data boundaries reconciled. No SQL executed.")
